import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

export async function getServerSideProps () {
  const {events_categories} = await import('../data/data.json');

  return{
    props:{
      data: events_categories,
    },
  };
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <h1> Events App </h1>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <a href='/'>Home</a>
          <a href='/events'>Events</a>
          <a href='/about-us'>About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
       {data.map ((ev) => 
        <a key={ev.id} href={'/events/${ev.id}'}>
          <Image width ={300} height={300} alt={ev.title} src={ev.image}/>
          <h2>{ev.title}</h2>
          <p> {ev.description}</p>
        </a>
        )}
      </main>
      <footer className={styles.footer}>
        <p> © 2023 Events App - Sapir Lavie</p>
      </footer>
    </>
  )
}
